services:
  db:
    image: postgres
    restart: always
    container_name: postgres-db
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: 1234
    networks:
      - network_1
  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 8080:8080
    container_name: spring-web
    networks:
      - network_1

networks:
  network_1:

volumes:
  postgres_volume:
    external: true
